FROM alpine:latest
RUN apk add --no-cache libstdc++
RUN wget -O vscode.tar.gz "https://code.visualstudio.com/sha/download?build=stable&os=linux-arm64"
RUN tar -xzf vscode.tar.gz && mv VSC* vscode
ENTRYPOINT ["./vscode/bin/code"]
